### ISSUE TITLE
Why is the reading and writing speed of kvdk not as fast as leveldb on ssd?

### ISSUE THREAD

**Issue by yunxiao3** [pmem/kvdk#121]
Why is the reading and writing speed of kvdk not as fast as leveldb? I think this is very strange. Is it the problem of my use or the problem of kvdb itself? If it is the problem of kvdb itself, do you have a good recommendation for kv database, it is best to use B+ tree as the engine, thank you.

**Comment by yunxiao3** [comment]
I test their performance by using the following code:


 ` 
        startTime = clock();
        for (int i = 0; i < kNumOps * 2; i++) {
                std::string key = keys[i % kNumKVs];
                std::string res;
                s = db_->Get( key, &res);
                s = db_->Set( key, res);
        }
        endTime = clock();

`

**Comment by KVKIT** [comment]
Xiaoyun, 
Yes, it's a bit strange. Per our experiments, the QPS of KVDK is at least more than an order of magnitude compared to leveldb. Could you please provide the full test code and your hardware configuration (CPU type, PMEM capacity, etc.)?

**Comment by yunxiao3** [comment]
thank you, peifeng. I think there is something wrong with my configuration, the following is my test codes and my benchmark server's config

Test code:

kvdk_test.cc 
https://paste.ubuntu.com/p/Xf6ZRHk2yS/
leveldb_test.cc
https://paste.ubuntu.com/p/MkTgpJmgFg/

Software and hardware config:

Ubuntu 20.04.1 LTS
72  Intel(R) Xeon(R) Gold 6240C CPU @ 2.60GHz
HDD  TOSHIBA  AL15SEB24EQY 2.2TB (not ssd)
pmem's config
{
	"dev":"namespace0.0",
	"mode":"fsdax",
	"map":"dev",
	"size":317087285248,
	"uuid":"518d0196-5c77-4ca4-8a61-da6bf95caa93",
	"sector_size":512,
	"align":2097152,
	"blockdev":"pmem0",
	"name":"nvmsilkstore"
}

**Comment by KVKIT** [comment]
Hi Yunxiao, Thank you for sharing the test code. Some comments of it:
1. The value of kNumOps and kNumKVs for kvdk_test.cc and leveldb_test.cc are not the same one.
2. You'd better enable sync of the write_option in leveldb, otherwise, it just puts kv into page cache.
for example:
`c++
        leveldb::WriteOptions write_options_;
        write_options_ = leveldb::WriteOptions();
        write_options_.sync = true;
        //...
        db_->Put(write_options_,key, value);
`

BTW, I saw you use 100*100 bytes for value size, could you share which scenario needs such a bit large value?

**Comment by yunxiao3** [comment]
> Hi Yunxiao, Thank you for sharing the test code. Some comments of it:
> 
> 1. The value of kNumOps and kNumKVs for kvdk_test.cc and leveldb_test.cc are not the same one.
> 2. You'd better enable sync of the write_option in leveldb, otherwise, it just puts kv into page cache.
>    for example:
>    `c++ leveldb::WriteOptions write_options_; write_options_ = leveldb::WriteOptions(); write_options_.sync = true; //... db_->Put(write_options_,key, value); `
> 
> BTW, I saw you use 100*100 bytes for value size, could you share which scenario needs such a bit large value?

Thank you for pointing out such a low-level error. I just found that the previous test code‘s ops number was inconsistent.   I have solved the problem, kvdk is indeed an order of magnitude faster than leveldb
At present, I need to use a kv database with acid feature to replace leveldb for indexing, but the value to be maintained is large, which is equivalent to some meta data. The bottleneck of the system is read operation, so when I found kvdk, I thought this should be what I wanted.
Thank you very much.

**Comment by yunxiao3** [comment]
Thank Peifeng for his help.
