### ISSUE TITLE
Wechat group QR code has expired

### ISSUE THREAD

**Issue by yunxiao3** [pmem/kvdk#143]
Can you update the wechat group QR code?

**Comment by KVKIT** [comment]
![kvdk_wechat_expired_Dec-20](https://user-images.githubusercontent.com/39690374/145811464-348c2503-3760-4d41-bb20-add85f5d3de1.jpg)

**Comment by ChrisZMF** [comment]
QR code has expired @KVKIT

**Comment by DawsonOne** [comment]
QR code has expired @KVKIT

**Comment by KVKIT** [comment]
![9f3e476581914bcfea65746a2633d34](https://user-images.githubusercontent.com/39690374/147717707-b8798579-1eec-468f-9a60-077b8982c778.jpg)

**Comment by ZiyanShi** [comment]
![mmqrcode1640832540612](https://user-images.githubusercontent.com/86653228/147717773-ad884917-75a6-46fb-979c-c0ed46d37a0f.png)

**Comment by superhail** [comment]
expired

**Comment by KVKIT** [comment]
![3c4f31ad2904eeb37b4121468728d68](https://user-images.githubusercontent.com/39690374/149056804-fa8c4b72-053a-4be1-a57f-c7488d8e6831.jpg)

**Comment by KVKIT** [comment]
![8c8936dd55ae6c85c7b886cd41db889](https://user-images.githubusercontent.com/39690374/149866556-b4f7787f-1918-46a1-ab1e-f19b03bf2bb0.jpg)

**Comment by KVKIT** [comment]
![f97a4248ae40011facc9ecfe94955e2](https://user-images.githubusercontent.com/39690374/151657299-34db36ec-38ee-4046-a2ff-d7cfd333dca8.jpg)

**Comment by KVKIT** [comment]
![9f2dfa25b1a5701a5ede1b18bb0ed02](https://user-images.githubusercontent.com/39690374/152739104-90a2f268-ccc0-4f84-99b1-0a44a3cca3f0.jpg)

**Comment by KVKIT** [comment]
![8891375708f40470506dc59ebdc43b0](https://user-images.githubusercontent.com/39690374/155282469-cd795ac4-6585-4d03-a25f-0986ce043532.jpg)

**Comment by danclive** [comment]
QR code has expired @KVKIT

**Comment by KVKIT** [comment]
![c850c8a9439fd16c18956a3d4a8aa82](https://user-images.githubusercontent.com/39690374/156504225-88ddf71b-872c-4381-a8e9-e14bc56d8a09.jpg)

**Comment by KVKIT** [comment]
> QR code has expired @KVKIT

Thank you for your reminder. Updated.

**Comment by smdsbz** [comment]
Expired.
Tencent really should have provided a programmatic approach to auto-generate QR code for authorized organizations.

**Comment by KVKIT** [comment]
![2d305012ab5eea51f047e86cacf91a2](https://user-images.githubusercontent.com/39690374/166422994-0a854d80-4d04-4dd3-9b0b-b3f1878e5687.jpg)

**Comment by KVKIT** [comment]
> Expired. Tencent really should have provided a programmatic approach to auto-generate QR code for authorized organizations.

Updated. Thank you for the reminder, I always forget to update it.

**Comment by KVKIT** [comment]
![dccbc5787af6c642cbfe836ac5a333b](https://user-images.githubusercontent.com/39690374/167535398-56df48f2-bf2a-4d92-b935-a0f6cfa2948b.jpg)

**Comment by KVKIT** [comment]
![7290e61f5bed158b334117d36800da9](https://user-images.githubusercontent.com/39690374/169771229-e2a914ba-eb63-4537-acfe-ca7a47efbecb.jpg)

**Comment by buaacen** [comment]
QR code has expired. @KVKIT

**Comment by KVKIT** [comment]
![1f0ebfe6db65fc7e79e67356aa92d19](https://user-images.githubusercontent.com/39690374/176183890-c860e1db-5761-4a16-904c-20d17ab8fa6b.jpg)

**Comment by fangneverdown** [comment]
QR code has expired. @KVKIT

**Comment by KVKIT** [comment]
> QR code has expired. @KVKIT

![2ad9636be44d6cfd092b0953bf8cd8c](https://user-images.githubusercontent.com/39690374/177490977-f63be4a5-36f0-430e-bfeb-6a525350cdd2.jpg)

**Comment by hhusjr** [comment]
QR code has expired. @KVKIT

**Comment by peifengsi** [comment]
![061e974bddc8ef2ce7fd47f0b546384](https://user-images.githubusercontent.com/39690374/197382156-a83f1af9-f95f-4fcc-a38a-21073e6dd490.jpg)
