### ISSUE TITLE
segment fault happen at insert and update of sort type 

### ISSUE THREAD

**Issue by Sean58238** [pmem/kvdk#15]
Segmentation fault      (core dumped) numactl --cpunodebind=0 --membind=0 ./bench -latency=1 -populate=1 -value_size=4096 -threads=64 -time=10 -path=/mnt/pmem0/kvdk -num=26163299 -space=536870912000 -max_write_threads=64 -fill=0 -type=sorted -read_ratio=0 -existing_keys_ratio=0 > ./results/sorted_vs4096_insert_thread64

Segmentation fault      (core dumped) numactl --cpunodebind=0 --membind=0 ./bench -latency=1 -populate=1 -value_size=4096 -threads=64 -time=10 -path=/mnt/pmem0/kvdk -num=26163299 -space=536870912000 -max_write_threads=64 -fill=0 -type=sorted -read_ratio=0 > ./results/sorted_vs4096_update_thread64

 please take a look.

**Comment by KVKIT** [comment]
Fixed at commit ede598a207dee9293b58823c2a28790d986bfd4b
Please have a try again. thanks!

**Comment by Sean58238** [comment]
issue not happened with sort type and latency disable
