### ISSUE TITLE
[NEW] KVDK need to have the KV expire capability to support a lot of related Redis commands.

### ISSUE THREAD

**Issue by chencheng1560** [pmem/kvdk#197]
**The problem/use-case that the feature addresses**

One of Redis's key features is that it allows data structures to set an expire times. Currently KVDK do not provide the KV expire capability

**Description of the feature**

We expect KVDK to provide the option to set the expiry time when executing commands such as Set, Get, etc. This feature will also be used to implement the redis command such as command TTL, EXPIRE, etc. 

**Alternatives you've considered**

No

**Additional information**

No

**Comment by KVKIT** [comment]
We will support this function with a patch series, about 3 patches. Please stay tuned :)
