### ISSUE TITLE
[NEW] Implement a Read-Modify-Write API to help improve the performance of commands like incr.

### ISSUE THREAD

**Issue by chencheng1560** [pmem/kvdk#198]
**The problem/use-case that the feature addresses**

There are a series number of Redis commands such as INCR, DECR, etc, which increase/decrease the value atomically. To support such commands effectively, we need a Read-Modify-Write API.

**Alternatives you've considered**

We can implement such function outside, but it is not very efficient 

**Additional information**

No

**Comment by JiayuZzz** [comment]
Implemented #212
