### ISSUE TITLE
[NEW] Need to support snapshot dump/restore as the RDB dump in Redis.

### ISSUE THREAD

**Issue by chencheng1560** [pmem/kvdk#199]
**The problem/use-case that the feature addresses**

There are a series of Redis commands, such as DUMP and RESTORE, which are used to dump the database as a snapshot and restore it somewhere. We hope such functions can be supported by KVDK.

**Comment by JiayuZzz** [comment]
Implemented #274 , kvdk can be backup to / restore from a log file, the behavior is similar to RDB dump in Redis
