### ISSUE TITLE
Cannot compile kvrocks

### ISSUE THREAD

**Issue by Chris-NaN** [pmem/kvdk#275]
## Bug Report
I cannot compile the kvrocks correctly by following the steps mentioned in the example/kvrocks/README
I found that the README is updated 9 months ago. However, the patch is updated three days ago.

### Current behavior
When I compile with running ‘make’, there's an error:
```
incubator-kvrocks/external/kvdk/include/types.hpp:7:10: fatal error: libpmemobj++/string_view.hpp: No such file or directory
```
This error could be fixed by copying `libpmemobj++/` directory from kvdk to the kvrocks.

But there is another error:
```
In file included from redis_bitmap_string.cc:5:
redis_string.h:9:10: fatal error: namespace.hpp: No such file or directory
#include "namespace.hpp"
```

I found that you are developing kvdk and there is no `namespace.h` file in the latest version. I would be grateful if you fixing the issue and update the README.

**Comment by KVKIT** [comment]
Thank you for reporting this issue. It was fixed in commit 9b7598, please try it out.

**Comment by Chris-NaN** [comment]
It works! Thank you very much!

**Comment by KVKIT** [comment]
You're welcome. I will close it.
