### ISSUE TITLE
[NEW] provide an option to define whether KVDKModify function will erase the original TTL

### ISSUE THREAD

**Issue by chencheng1560** [pmem/kvdk#309]
**The problem/use-case that the feature addresses**

A description of the problem that the feature will solve, or the use-case with which the feature will be used.

The KVDKModify functions will erase the exist TTL by default. But sometime we prefer to keep current TTL.

**Description of the feature**

A description of what you want to happen.

Can we provide an option to indicate that whether the KVDKModify function will erase the original TTL or keep it.

**Alternatives you've considered**

Any alternative solutions or features you've considered, including references to existing open and closed feature requests in this repository.

**Additional information**

Any additional information that is relevant to the feature request.

**Comment by JiayuZzz** [comment]
#315
