### ISSUE TITLE
[NEW]

### ISSUE THREAD

**Issue by fangneverdown** [pmem/kvdk#312]
when will the next release version of kvdk be committed?
The release version now is v_0.2. I noticed this version's batchwrite was incompeleted and recently you have added the feature of batchwrite. I would like to know the current stage of this project and what I need to pay attention to if implementing kvdk into my project?

**Comment by KVKIT** [comment]
Hi there, we are working on the transaction feature and plan to release the official v1.0 around Aug 31st.  The latest code has more complete support for batch write, so we suggest you give it a try. We welcome any questions and suggestions and will address them promptly.

**Comment by fangneverdown** [comment]
thank you!
