### ISSUE TITLE
PMEMAllocator does not correctly populate PMEM space

### ISSUE THREAD

**Issue by tthebst** [pmem/kvdk#50]
Populate space sometimes fails to initialize the pmem space.  In `PMEMAllocator::PopulateSpace` it is possible that `pmem_memset` gets called on memory that is not part of the file. It happens if `pu` (cpu count) is not a power of 2. In my case `pu` was 12 and I used [linux memmap](https://docs.pmem.io/persistent-memory/getting-started-guide/creating-development-environments/linux-environments/linux-memmap). This caused a segmentation fault.

Reproduce:
- Setup [linux memmap](https://docs.pmem.io/persistent-memory/getting-started-guide/creating-development-environments/linux-environments/linux-memmap)
- Run tutorial
- Check that `pu` is 12

Solutions: 
- Always set `pu` to `16` as done [here](https://github.com/pmem/kvdk/blob/717a91bc6480503f98a52696d2f26a72d9288476/engine/pmem_allocator/pmem_allocator.cpp#L28) and check file is the power of 2
- Handle edge case for cases where cpu count not power of two

**Comment by JiayuZzz** [comment]
Thanks for submitting, problem resolved #51
