### ISSUE TITLE
Segmentation fault after recovering

### ISSUE THREAD

**Issue by ZiyanShi** [pmem/kvdk#60]
Branch: `pmem/kvdk/main:19332d5`
Binary is built under `kvdk/build/` by calling `cmake ..` and `make -j`
Then the old directory under pmem is cleared to create a new instance by calling
`rm -rf /mnt/pmem0/debugging2`
The new engine is created by
`./bench -populate=1 -value_size=120 -threads=1 -time=10 -path=/mnt/pmem0/debugging2 -num=1048576 -space=209715200 -max_write_threads=1 -collections=1 -type=sorted -fill=1`
and then closed.
Then the engine is reopened, trying to be restored, which will trigger segment error.
`./bench -populate=1 -value_size=120 -threads=1 -time=10 -path=/mnt/pmem0/debugging2 -num=1048576 -space=209715200 -max_write_threads=1 -collections=1 -type=sorted -fill=0 -read_ratio=1`

**Comment by KVKIT** [comment]
fix in #62
