### ISSUE TITLE
Try to use devdax to replace the fsdax

### ISSUE THREAD

**Issue by BaronStack** [pmem/kvdk#72]
problem: Fsdax model in kvdk will let request go into the kernel vfs system and  this model will extend the critical path of the request.

improv: Devdax could bypass the os-fs，and access the pmem directly, it's benefit for kvdk's work model.

We will upload the pr for support devdax in kvdk.

zhanghuigui@kuaishou.com

**Comment by KVKIT** [comment]
Good suggestion, but I would suggest to add devdax support as an option instead of replacing fsdax since in some environments KVDK may use fsdax together with other workloads.

**Comment by BaronStack** [comment]
Yes, an option will be supported to use devdax.
